export const ALL_CATEGORY_REQUEST = 'ALL_CATEGORY_REQUEST'
export const ALL_CATEGORY_SUCCESS = 'ALL_CATEGORY_SUCCESS'
export const ALL_CATEGORY_FAIL = 'ALL_CATEGORY_FAIL'


export const SINGLE_CATEGORY_REQUEST = 'SINGLE_CATEGORY_REQUEST'
export const SINGLE_CATEGORY_SUCCESS = 'SINGLE_CATEGORY_SUCCESS'
export const SINGLE_CATEGORY_FAIL = 'SINGLE_CATEGORY_FAIL'

export const ADMIN_CATEGORY_REQUEST = 'ADMIN_CATEGORY_REQUEST'
export const ADMIN_CATEGORY_SUCCESS = 'ADMIN_CATEGORY_SUCCESS'
export const ADMIN_CATEGORY_FAIL = 'ADMIN_CATEGORY_FAIL'