export const ALL_GIRLS_REQUEST = 'ALL_GIRLS_REQUEST'
export const ALL_GIRLS_SUCCESS = 'ALL_GIRLS_SUCCESS'
export const ALL_GIRLS_ERROR = 'ALL_GIRLS_ERROR'

export const SINGLE_GIRL_REQUEST = 'SINGLE_GIRL_REQUEST'
export const SINGLE_GIRL_SUCCESS = 'SINGLE_GIRL_SUCCESS'
export const SINGLE_GIRL_FAIL = 'SINGLE_GIRL_FAIL'

export const VOTE_GIRL_REQUEST = ' VOTE_GIRL_REQUEST'
export const VOTE_GIRL_SUCCESS = ' VOTE_GIRL_SUCCESS'
export const VOTE_GIRL_FAIL = ' VOTE_GIRL_FAIL'
export const VOTE_GIRL_RESET = ' VOTE_GIRL_RESET'

export const GET_COVERGIRL_COMPETITION_REQUEST =
	'GET_COVERGIRL_COMPETITION_REQUEST'
export const GET_COVERGIRL_COMPETITION_SUCCESS =
	'GET_COVERGIRL_COMPETITION_SUCCESS'
export const GET_COVERGIRL_COMPETITION_FAIL = 'GET_COVERGIRL_COMPETITION_FAIL'
