export const ALL_POST_START = 'ALL_POST_START'
export const ALL_POST_SUCCESS = 'ALL_POST_SUCCESS'
export const ALL_POST_FAIL = 'ALL_POST_FAIL'

export const TAB_POST_REQUEST = 'TAB_POST_REQUEST'
export const TAB_POST_SUCCESS = 'TAB_POST_SUCCESS'
export const TAB_POST_FAIL = 'TAB_POST_FAIL'

export const TOP_STORIES_REQUEST = 'TOP_STORIES_REQUEST'
export const TOP_STORIES_SUCCESS = 'TOP_STORIES_SUCCESS'
export const TOP_STORIES_FAIL = 'TOP_STORIES_FAIL'

export const TODAYS_TAKE_REQUEST = 'TODAYS_TAKE_REQUEST'
export const TODAYS_TAKE_SUCCESS = 'TODAYS_TAKE_SUCCESS'
export const TODAYS_TAKE_FAIL = 'TODAYS_TAKE_FAIL'

export const SINGLE_POST_REQUEST = 'SINGLE_POST_REQUEST'
export const SINGLE_POST_SUCCESS = 'SINGLE_POST_SUCCESS'
export const SINGLE_POST_FAIL = 'SINGLE_POST_FAIL'

export const CATEGORY_POSTS_REQUEST = 'CATEGORY_POSTS_REQUEST'
export const CATEGORY_POSTS_SUCCESS = 'CATEGORY_POSTS_SUCCESS'
export const CATEGORY_POSTS_FAIL = 'CATEGORY_POSTS_FAIL'
