export const ALL_POST_START = 'ALL_POST_START'
export const ALL_POST_SUCCESS = 'ALL_POST_SUCCESS'
export const ALL_POST_FAIL = 'ALL_POST_FAIL'

export const TAB_POST_REQUEST = 'TAB_POST_REQUEST'
export const TAB_POST_SUCCESS = 'TAB_POST_SUCCESS'
export const TAB_POST_FAIL = 'TAB_POST_FAIL'

export const TOP_STORIES_REQUEST = 'TOP_STORIES_REQUEST'
export const TOP_STORIES_SUCCESS = 'TOP_STORIES_SUCCESS'
export const TOP_STORIES_FAIL = 'TOP_STORIES_FAIL'

export const TODAYS_TAKE_REQUEST = 'TODAYS_TAKE_REQUEST'
export const TODAYS_TAKE_SUCCESS = 'TODAYS_TAKE_SUCCESS'
export const TODAYS_TAKE_FAIL = 'TODAYS_TAKE_FAIL'

export const SINGLE_POST_REQUEST = 'SINGLE_POST_REQUEST'
export const SINGLE_POST_SUCCESS = 'SINGLE_POST_SUCCESS'
export const SINGLE_POST_FAIL = 'SINGLE_POST_FAIL'

export const CATEGORY_POSTS_REQUEST = 'CATEGORY_POSTS_REQUEST'
export const CATEGORY_POSTS_SUCCESS = 'CATEGORY_POSTS_SUCCESS'
export const CATEGORY_POSTS_FAIL = 'CATEGORY_POSTS_FAIL'

export const GET_ALL_POST_ADMIN_REQUEST = 'GET_ALL_POST_ADMIN_REQUEST'
export const GET_ALL_POST_ADMIN_SUCCESS = 'GET_ALL_POST_ADMIN_SUCCESS'
export const GET_ALL_POST_ADMIN_FAIL = 'GET_ALL_POST_ADMIN_FAIL'
export const GET_ALL_POST_ADMIN_RESET = 'GET_ALL_POST_ADMIN_RESET'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAIL = ' EDIT_POST_FAIL'
export const EDIT_POST_RESET = 'EDIT_POST_RESET'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'
export const UPDATE_POST_RESET = 'UPDATE_POST_RESET'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'
export const CREATE_POST_RESET = 'CREATE_POST_RESET'

export const TOGGLE_PUBLISH_UNPUBLISH_REQUEST =
	'TOGGLE_PUBLISH_UNPUBLISH_REQUEST'
export const TOGGLE_PUBLISH_UNPUBLISH_SUCCESS =
	'TOGGLE_PUBLISH_UNPUBLISH_SUCCESS'
export const TOGGLE_PUBLISH_UNPUBLISH_FAIL = 'TOGGLE_PUBLISH_UNPUBLISH_FAIL'
